### ISSUE TITLE
Suggestion - Allow us to choose backpacks from within the DLL

### ISSUE THREAD

**Issue by cool-nite** [PeQuLeaks/NeonitePP-Fixed#3]
Currently we can't select what backpacks the player wears from within the DLL , at least from what i've seen (backpacks don't appear to work at all) , so we can't do Skyfire backpacks

which is annoying

(yes i did try to add serverchoosepart but it simply just crashed)

**Comment by PeQuLeaks** [comment]
This is a open source project, diy.

**Comment by cool-nite** [comment]
(maybe i would do it myself if i had any idea on whatever the what epic games did to server choose part)
